version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_estoque
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: estoque
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
